name: build-and-publish

on: 
  workflow_dispatch:
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Install opm from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          opm: "latest"
      
      - name: Install skopeo
        run: |
          sudo apt-get -y install skopeo

      - name: Install yq
        env:
          VERSION: v4.14.2
          BINARY: yq_linux_amd64
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Publish
        run: ./hack/build.sh "quay.io/jcho0/cert-manager-operator:test" "quay.io/jcho0/cert-manager-operator-bundle:test" "quay.io/jcho0/cert-manager-operator-index:test" 
